CREATE DATABASE VET;
USE VET;

CREATE TABLE CLIENTES(
    ID INT PRIMARY KEY NOT NULL AUTO_INCREMENT,
    NOMBRES VARCHAR(50),
    APELLIDOS VARCHAR(50),
    DNI VARCHAR(8),
    TELEFONO VARCHAR(15),
    DIRECCION TEXT,
    EMAIL VARCHAR(50),
    CREACION DATETIME,
    ACTUALIZACION DATETIME
)

CREATE PROCEDURE SP_INSERTAR_CLIENTE(PNOMBRES VARCHAR(50), PAPELLIDOS VARCHAR(50), PDNI VARCHAR(8), PTELEFONO VARCHAR(15), PDIRECCION TEXT, PEMAIL VARCHAR(50)) INSERT INTO CLIENTES (NOMBRES, APELLIDOS, DNI, TELEFONO, DIRECCION, EMAIL, CREACION, ACTUALIZACION) VALUES (PNOMBRES, PAPELLIDOS, PDNI, PTELEFONO, PDIRECCION, PEMAIL, NOW(), NOW());
CREATE PROCEDURE SP_EDITAR_CLIENTE(PNOMBRES VARCHAR(50), PAPELLIDOS VARCHAR(50), PDNI VARCHAR(8), PTELEFONO VARCHAR(15), PDIRECCION TEXT, PEMAIL VARCHAR(50)) UPDATE CLIENTES SET NOMBRES=PNOMBRES, APELLIDOS=PAPELLIDOS, DNI=PDNI, TELEFONO=PTELEFONO, DIRECCION=PDIRECCION, EMAIL=PEMAIL, ACTUALIZACION=NOW()  WHERE DNI=PDNI;
CREATE PROCEDURE SP_ELIMINAR_CLIENTE(PDNI VARCHAR(8)) DELETE FROM CLIENTES WHERE DNI=PDNI;

CREATE TABLE RECEPCIONISTAS(
    ID INT PRIMARY KEY NOT NULL AUTO_INCREMENT,
    NOMBRES VARCHAR(50),
    APELLIDOS VARCHAR(50),
    DNI VARCHAR(8),
    TELEFONO VARCHAR(15),
    DIRECCION TEXT,
    CREACION DATETIME,
    ACTUALIZACION DATETIME
)

CREATE PROCEDURE SP_INSERTAR_RECEPCIONISTA(PNOMBRES VARCHAR(50), PAPELLIDOS VARCHAR(50), PDNI VARCHAR(8), PTELEFONO VARCHAR(15), PDIRECCION TEXT) INSERT INTO RECEPCIONISTAS (NOMBRES, APELLIDOS, DNI, TELEFONO, DIRECCION, CREACION, ACTUALIZACION) VALUES (PNOMBRES, PAPELLIDOS, PDNI, PTELEFONO, PDIRECCION, NOW(), NOW());
CREATE PROCEDURE SP_EDITAR_RECEPCIONISTA(PNOMBRES VARCHAR(50), PAPELLIDOS VARCHAR(50), PDNI VARCHAR(8), PTELEFONO VARCHAR(15), PDIRECCION TEXT) UPDATE RECEPCIONISTAS SET NOMBRES=PNOMBRES, APELLIDOS=PAPELLIDOS, DNI=PDNI, TELEFONO=PTELEFONO, DIRECCION=PDIRECCION, ACTUALIZACION=NOW()  WHERE DNI=PDNI;
CREATE PROCEDURE SP_ELIMINAR_RECEPCIONISTA(PDNI VARCHAR(8)) DELETE FROM RECEPCIONISTAS WHERE DNI=PDNI;

CREATE TABLE VETERINARIOS(
    ID INT PRIMARY KEY NOT NULL AUTO_INCREMENT,
    NOMBRES VARCHAR(50),
    APELLIDOS VARCHAR(50),
    DNI VARCHAR(8),
    TELEFONO VARCHAR(15),
    DIRECCION TEXT,
    CREACION DATETIME,
    ACTUALIZACION DATETIME
)

CREATE PROCEDURE SP_INSERTAR_VETERINARIO(PNOMBRES VARCHAR(50), PAPELLIDOS VARCHAR(50), PDNI VARCHAR(8), PTELEFONO VARCHAR(15), PDIRECCION TEXT) INSERT INTO VETERINARIOS (NOMBRES, APELLIDOS, DNI, TELEFONO, DIRECCION, CREACION, ACTUALIZACION) VALUES (PNOMBRES, PAPELLIDOS, PDNI, PTELEFONO, PDIRECCION, NOW(), NOW());
CREATE PROCEDURE SP_EDITAR_VETERINARIO(PNOMBRES VARCHAR(50), PAPELLIDOS VARCHAR(50), PDNI VARCHAR(8), PTELEFONO VARCHAR(15), PDIRECCION TEXT) UPDATE VETERINARIOS SET NOMBRES=PNOMBRES, APELLIDOS=PAPELLIDOS, DNI=PDNI, TELEFONO=PTELEFONO, DIRECCION=PDIRECCION, ACTUALIZACION=NOW()  WHERE DNI=PDNI;
CREATE PROCEDURE SP_ELIMINAR_VETERINARIO(PDNI VARCHAR(8)) DELETE FROM VETERINARIOS WHERE DNI=PDNI;

CREATE TABLE MASCOTAS(
    ID INT PRIMARY KEY NOT NULL AUTO_INCREMENT,
    NOMBRE VARCHAR(25),
    EDAD VARCHAR(2),
    SEXO CHAR(1),
    COLOR VARCHAR(15),
    RAZA VARCHAR(25),
    PESO DECIMAL(3,1),
    ALTURA DECIMAL(3,1),
    CREACION DATETIME,
    ACTUALIZACION DATETIME
)

CREATE PROCEDURE SP_INSERTAR_MASCOTA(
    PNOMBRE VARCHAR(25), 
    PEDAD VARCHAR(2), 
    PSEXO VARCHAR(1), 
    PCOLOR VARCHAR(15), 
    PRAZA VARCHAR(25),
    PPESO DECIMAL(3,1),
    PALTURA DECIMAL(3,1))
INSERT INTO MASCOTAS (NOMBRE, EDAD, SEXO, COLOR, RAZA, PESO, ALTURA, CREACION, ACTUALIZACION) VALUES (PNOMBRE, PEDAD, PSEXO, PCOLOR, PRAZA, PPESO, PALTURA, NOW(), NOW());


CREATE PROCEDURE SP_EDITAR_MASCOTA(
    PID VARCHAR(11),
    PNOMBRE VARCHAR(25), 
    PEDAD VARCHAR(2), 
    PSEXO VARCHAR(1), 
    PCOLOR VARCHAR(15), 
    PRAZA VARCHAR(25),
    PPESO DECIMAL(3,1),
    PALTURA DECIMAL(3,1))
UPDATE MASCOTAS SET NOMBRE=PNOMBRE, EDAD=PEDAD, SEXO=PSEXO, COLOR=PCOLOR, RAZA=PRAZA, PESO=PPESO, ALTURA=PALTURA, ACTUALIZACION=NOW() WHERE ID=PID;


CREATE PROCEDURE SP_ELIMINAR_MASCOTA(PID VARCHAR(11)) DELETE FROM MASCOTAS WHERE ID=PID;


CREATE TABLE CITAS(
    ID INT PRIMARY KEY NOT NULL AUTO_INCREMENT,
    RECEPCIONISTA INT,
    VETERINARIO INT,
    CLIENTE INT,
    MASCOTA INT,
    ATENCION VARCHAR(15),
    CREACION DATETIME,
    ACTUALIZACION DATETIME,
    FOREIGN KEY (RECEPCIONISTA) REFERENCES RECEPCIONISTAS(ID),
    FOREIGN KEY (VETERINARIO) REFERENCES VETERINARIOS(ID),
    FOREIGN KEY (CLIENTE) REFERENCES CLIENTES(ID),
    FOREIGN KEY (MASCOTA) REFERENCES MASCOTAS(ID)
)


CREATE PROCEDURE SP_INSERTAR_CITA(
    PRECEPCIONISTA VARCHAR(11), 
    PVETERINARIO VARCHAR(11), 
    PCLIENTE VARCHAR(11), 
    PMASCOTA VARCHAR(11), 
    PATENCION VARCHAR(11)
)
INSERT INTO CITAS (RECEPCIONISTA, VETERINARIO, CLIENTE, MASCOTA, ATENCION, CREACION, ACTUALIZACION) 
VALUES (PRECEPCIONISTA, PVETERINARIO, PCLIENTE, PMASCOTA, PATENCION, NOW(), NOW());


CREATE PROCEDURE SP_EDITAR_CITA(
    PID VARCHAR(11), 
    PRECEPCIONISTA VARCHAR(11), 
    PVETERINARIO VARCHAR(11), 
    PCLIENTE VARCHAR(11), 
    PMASCOTA VARCHAR(11), 
    PATENCION VARCHAR(11)
)
UPDATE CITAS SET RECEPCIONISTA=PRECEPCIONISTA, VETERINARIO=PVETERINARIO, CLIENTE=PCLIENTE, MASCOTA=PMASCOTA, ATENCION=PATENCION, ACTUALIZACION=NOW() WHERE ID=PID;

CREATE PROCEDURE SP_ELIMINAR_CITA(PID VARCHAR(11)) DELETE FROM CITAS WHERE ID=PID;